# Generated by Django 5.1.1 on 2024-11-04 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_1', models.TextField()),
                ('option_2', models.TextField()),
                ('option_3', models.TextField()),
                ('option_4', models.TextField()),
                ('correct_option', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=50)),
                ('chapter_content', models.TextField()),
                ('assessments', models.ManyToManyField(related_name='chapter_assessments', to='course.assesment')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=50)),
                ('chapters', models.ManyToManyField(related_name='module_chapters', to='course.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_name', models.TextField(unique=True)),
                ('course_type', models.CharField(max_length=20)),
                ('deliverables', models.CharField(max_length=20)),
                ('modules', models.ManyToManyField(related_name='course_modules', to='course.module')),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='questions',
            field=models.ManyToManyField(related_name='assessment_questions', to='course.questions'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('attempted', models.BooleanField(default=False)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
            ],
        ),
    ]
