# Generated by Django 5.1.1 on 2024-11-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_chapteruser_user_id_userprogress_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
