# Generated by Django 5.1.1 on 2024-11-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_chapter_chapter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.TextField(unique=True),
        ),
    ]
