# Generated by Django 5.1.1 on 2024-11-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('classroom', '0002_classcourse_course_id_classmember_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.classroom'),
        ),
    ]
