# Generated by Django 5.1.1 on 2024-11-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='authentication.certifications'),
        ),
    ]
