# Generated by Django 5.1.1 on 2024-11-03 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_class_id'),
        ('classroom', '0002_classmember_member_classroom_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.classroom'),
        ),
    ]
