# Generated by Django 5.1.1 on 2024-11-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_courses_classroom_manager_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='courses',
        ),
    ]
