# Generated by Django 5.1.1 on 2024-11-05 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_classroom_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('curriculum_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('expected_meetings', models.IntegerField()),
                ('module_name', models.TextField()),
                ('detailed_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='curriculum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classroom.curriculum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='modules',
            field=models.ManyToManyField(related_name='curriculum_modules', to='classroom.modules'),
        ),
    ]
