# Generated by Django 5.1.1 on 2024-11-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroom_manager_id_alter_classmember_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
