# Generated by Django 5.1.1 on 2024-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_curriculum_modules_classroom_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='eod',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
