# Generated by Django 5.1.1 on 2024-11-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_classroom_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
