# Generated by Django 5.1.1 on 2024-11-07 06:32

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_userattendance_classroomattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('meeting_name', models.TextField()),
                ('meeting_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('meeting_date', models.DateField(default=datetime.date.today, unique=True)),
                ('meeting_link', models.URLField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('clasroom_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.classroom')),
                ('participants', models.ManyToManyField(related_name='meeting_participant', to=settings.AUTH_USER_MODEL)),
                ('trainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
