# Generated by Django 5.1.1 on 2024-11-08 04:49

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_classroom_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='meeting_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='meetings',
            unique_together={('classroom_id', 'meeting_date', 'trainer_id')},
        ),
    ]
