# Generated by Django 5.1.1 on 2024-11-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_meetings_conducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattendance',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClassRoomAttendance',
        ),
        migrations.DeleteModel(
            name='UserAttendance',
        ),
    ]
